web:
  command: gunicorn comkc.server:app --bind 0.0.0.0:8080 --worker-class aiohttp.worker.GunicornWebWorker
  extends:
    file: docker-compose.common.yml
    service: webapp
  links:
    - postgres
  ports:
    - "8080"

worker:
  command: python -m comkc.worker
  extends:
    file: docker-compose.common.yml
    service: webapp
  links:
    - postgres

uploader:
  command: python -m comkc.uploader
  extends:
    file: docker-compose.common.yml
    service: webapp
  links:
    - postgres

postgres:
  image: postgres:latest
  expose:
    - "5432"
