web:
  command: gunicorn comkc.server:app --bind 0.0.0.0:8080 --worker-class aiohttp.worker.GunicornWebWorker
  extends:
    file: docker-compose.common.yml
    service: webapp
  ports:
    - "8080"

worker:
  command: python -m comkc.worker
  extends:
    file: docker-compose.common.yml
    service: webapp

uploader:
  command: python -m comkc.uploader
  extends:
    file: docker-compose.common.yml
    service: webapp
