server:
  build: .
  command: gunicorn comkc.server:app --bind 0.0.0.0:8080 --worker-class aiohttp.worker.GunicornWebWorker
  links:
    - postgres
  environment:
    COMKC_PG_DSN: dbname=comkc user=comkc_user password=passwd host=postgres

worker:
  build: .
  command: python -m comkc.worker
  links:
    - postgres
  environment:
    COMKC_PG_DSN: dbname=comkc user=comkc_user password=passwd host=postgres

uploader:
  build: .
  command: python -m comkc.uploader
  links:
    - postgres
  environment:
    COMKC_PG_DSN: dbname=comkc user=comkc_user password=passwd host=postgres
    COMKC_QINIU_ACCESS_KEY: key
    COMKC_QINIU_SECRET_KEY: key
    COMKC_QINIU_BUCKET_NAME: name
    COMKC_QINIU_URL_FORMAT: url

postgres:
  image: postgres:latest
  ports:
    - 5432
